notifications:
  email: false

language: go

go:
  - 1.6
  - tip

script:
  # launch go test
  - make test

  # build all binaries for all possible platform
  - make build-all

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: "modulable-zork-releases"
  region: "eu-west-1"
  upload-dir: "releases/$TRAVIS_TAG"
  file:
    - "bin/modulable-zork_freebsd_amd64"
    - "bin/modulable-zork_linux_arm"
    - "bin/modulable-zork_openbsd_386"
    - "bin/modulable-zork_darwin_386"
    - "bin/modulable-zork_freebsd_arm"
    - "bin/modulable-zork_netbsd_386"
    - "bin/modulable-zork_openbsd_amd64"
    - "bin/modulable-zork_darwin_amd"
    - "bin/modulable-zork_linux_386"
    - "bin/modulable-zork_netbsd_amd"
    - "bin/modulable-zork_windows_386.exe"
    - "bin/modulable-zork_freebsd_38"
    - "bin/modulable-zork_linux_amd64"
    - "bin/modulable-zork_netbsd_arm"
    - "bin/modulable-zork_windows_amd64.exe"
  skip_cleanup: true
  on:
    tags: true
